DROP TABLE IF EXISTS USERS;
CREATE SEQUENCE user_seq;
CREATE SEQUENCE book_seq;
CREATE TABLE USERS(
                    ID BIGINT DEFAULT nextval('user_seq') PRIMARY KEY,
                    NAME varchar(40) NOT NULL,
                    PASSWORD varchar(60),
                    ACTIVE BOOLEAN NOT NULL,
                    UUID varchar(36),
                    LAST_LOGIN TIMESTAMP,
                    NUMBERS INTEGER[]
);


INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE, UUID, NUMBERS) VALUES (0, 'Demo', '1234', '2011-01-01 15:00:00', TRUE, '7dc53df5-703e-49b3-8670-b1c468f47f1f', '{12,13,14}');
INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE) VALUES (1, 'Admin', 'admin', '2011-01-01 16:00:00', TRUE);
INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE) VALUES (2, 'User', 'user', '2011-01-01 17:00:00', TRUE);



CREATE TABLE BOOKS(
                      ID BIGINT DEFAULT nextval('book_seq') PRIMARY KEY,
                      NAME varchar(40) NOT NULL,
                      USER_ID INTEGER REFERENCES USERS(ID)
);

INSERT INTO BOOKS(ID, NAME, USER_ID) VALUES (0, 'Alpha', 1);
INSERT INTO BOOKS(ID, NAME, USER_ID) VALUES (1, 'Beta', 1);
INSERT INTO BOOKS(ID, NAME, USER_ID) VALUES (2, 'Gamma', 1);
INSERT INTO BOOKS(ID, NAME, USER_ID) VALUES (3, 'Delta', 2);


ALTER SEQUENCE user_seq RESTART WITH 100;
ALTER SEQUENCE book_seq RESTART WITH 100;
