// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;

public class DropdownData<T> {
	private String label;
	private T value;


	public String getLabel() {
		return this.label;
	}


	public T getValue() {
		return this.value;
	}


	public void setLabel(final String label) {
		this.label = label;
	}


	public void setValue(final T value) {
		this.value = value;
	}

}
