// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;


public abstract class DSOBaseEntity {
	private Integer id;


	public DSOBaseEntity() {
	}


	public Integer getId() {
		return this.id;
	}


	public void setId(final Integer id) {
		this.id = id;
	}


}
