// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;



public class DSOGruppeEntity extends DSOBaseEntity {
	private String name;
	private Integer datum;
	private String image;

	public String getName() {
		return this.name;
	}

	public Integer getDatum() {
		return this.datum;
	}


	public void setName(final String name) {
		this.name = name;
	}

	public void setDatum(final Integer datum) {
		this.datum = datum;
	}


	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
}
