// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;


import java.math.BigInteger;
import java.util.Date;

public class DSOHeldEntity {
	private Long id;
	private Integer userId;
	private String name;
	private Date createdDate;
	private boolean isPublic;
	private boolean isActive = true;
	private boolean deleted;
	private DSOGruppeEntity gruppe;

	private Long key;
	private Date lockExpire;

	public DSOHeldEntity() {
	}

	public Long getId() {
		return this.id;
	}


	public Integer getUserId() {
		return this.userId;
	}


	public String getName() {
		return this.name;
	}


	public Date getCreatedDate() {
		return this.createdDate;
	}


	public boolean isPublic() {
		return this.isPublic;
	}


	public boolean isActive() {
		return this.isActive;
	}


	public boolean isDeleted() {
		return this.deleted;
	}


	public DSOGruppeEntity getGruppe() {
		return this.gruppe;
	}


	public void setId(final Long id) {
		this.id = id;
	}


	public void setUserId(final Integer userId) {
		this.userId = userId;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setCreatedDate(final Date createdDate) {
		this.createdDate = createdDate;
	}


	public void setPublic(final boolean isPublic) {
		this.isPublic = isPublic;
	}


	public void setActive(final boolean isActive) {
		this.isActive = isActive;
	}


	public void setDeleted(final boolean deleted) {
		this.deleted = deleted;
	}


	public void setGruppe(final DSOGruppeEntity gruppe) {
		this.gruppe = gruppe;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public Date getLockExpire() {
		return lockExpire;
	}

	public void setLockExpire(Date lockExpire) {
		this.lockExpire = lockExpire;
	}
}
