// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;

import java.util.Date;

public class DSOHeldVersion {
	private String letztesAbenteuer;
	private Date datum;
	private int version;


	public String getLetztesAbenteuer() {
		return this.letztesAbenteuer;
	}


	public Date getDatum() {
		return this.datum;
	}


	public int getVersion() {
		return this.version;
	}


	public void setLetztesAbenteuer(final String letztesAbenteuer) {
		this.letztesAbenteuer = letztesAbenteuer;
	}


	public void setDatum(final Date datum) {
		this.datum = datum;
	}


	public void setVersion(final int version) {
		this.version = version;
	}

	public DSOHeldVersion() {

	}
}
