// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.rest.synchronization;

import java.math.BigInteger;
import java.util.Date;

public class HeldenInfo {
	private String name;
	private Date lastChanged;
	private int version;
	private String gruppe;
	private Long id;
	private boolean oeffentlich;
	private boolean active;


	public String getName() {
		return this.name;
	}


	public Date getLastChanged() {
		return this.lastChanged;
	}


	public int getVersion() {
		return this.version;
	}


	public String getGruppe() {
		return this.gruppe;
	}


	public Long getId() {
		return this.id;
	}


	public boolean isOeffentlich() {
		return this.oeffentlich;
	}


	public boolean isActive() {
		return this.active;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setLastChanged(final Date lastChanged) {
		this.lastChanged = lastChanged;
	}


	public void setVersion(final int version) {
		this.version = version;
	}


	public void setGruppe(final String gruppe) {
		this.gruppe = gruppe;
	}


	public void setId(final Long id) {
		this.id = id;
	}


	public void setOeffentlich(final boolean oeffentlich) {
		this.oeffentlich = oeffentlich;
	}


	public void setActive(final boolean active) {
		this.active = active;
	}
}
