// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.integration.user;

public class UserRegistration {
    private String name;
    private String password;
    private String token;
    private String gruppe;
    private Long role;
    private Boolean heldenPublic;


    public String getName() {
        return this.name;
    }


    public String getPassword() {
        return this.password;
    }


    public String getToken() {
        return this.token;
    }


    public String getGruppe() {
        return this.gruppe;
    }


    public void setName(final String name) {
        this.name = name;
    }


    public void setPassword(final String password) {
        this.password = password;
    }


    public void setToken(final String token) {
        this.token = token;
    }


    public void setGruppe(final String gruppe) {
        this.gruppe = gruppe;
    }

    public Long getRole() {
        return role;
    }

    public void setRole(Long role) {
        this.role = role;
    }

    public Boolean getHeldenPublic() {
        return heldenPublic;
    }

    public void setHeldenPublic(Boolean heldenPublic) {
        this.heldenPublic = heldenPublic;
    }

    public UserRegistration() {
    }


    public UserRegistration(final String name, final String password, final String token, final String gruppe) {
        this.name = name;
        this.password = password;
        this.token = token;
        this.gruppe = gruppe;
    }
}
