//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.26 at 12:11:01 PM CET 
//


package de.failender.heldensoftware.xml.datenxml;

import de.failender.heldensoftware.Unterscheidbar;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}getName"/>
 *         &lt;element ref="{}meisterhandwerk"/>
 *         &lt;element ref="{}leittalent"/>
 *         &lt;element ref="{}basis"/>
 *         &lt;element ref="{}nameausfuehrlich"/>
 *         &lt;element ref="{}wert"/>
 *         &lt;element ref="{}probe"/>
 *         &lt;element ref="{}probenwerte"/>
 *         &lt;element ref="{}nameausfuehrlichmitprobe"/>
 *         &lt;element ref="{}at" minOccurs="0"/>
 *         &lt;element ref="{}pa" minOccurs="0"/>
 *         &lt;element ref="{}sprachkomplexitaet" minOccurs="0"/>
 *         &lt;element ref="{}muttersprache" minOccurs="0"/>
 *         &lt;element ref="{}schriftmuttersprache" minOccurs="0"/>
 *         &lt;element ref="{}zweitlehrsprache" minOccurs="0"/>
 *         &lt;element ref="{}behinderung"/>
 *         &lt;element ref="{}mirakelplus"/>
 *         &lt;element ref="{}mirakelminus"/>
 *         &lt;element ref="{}metatalent"/>
 *         &lt;element ref="{}bereich"/>
 *         &lt;element ref="{}komplexitaet"/>
 *         &lt;element ref="{}lernkomplexitaet"/>
 *         &lt;element ref="{}spezialisierungen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "meisterhandwerk",
    "leittalent",
    "basis",
    "nameausfuehrlich",
    "wert",
    "probe",
    "probenwerte",
    "nameausfuehrlichmitprobe",
    "at",
    "pa",
    "sprachkomplexitaet",
    "muttersprache",
    "schriftmuttersprache",
    "zweitlehrsprache",
    "behinderung",
    "mirakelplus",
    "mirakelminus",
    "metatalent",
    "bereich",
    "komplexitaet",
    "lernkomplexitaet",
    "spezialisierungen"
})
@XmlRootElement(name = "talent")
public class Talent implements Unterscheidbar {

    @XmlElement(required = true)
    protected String name;
    protected boolean meisterhandwerk;
    protected boolean leittalent;
    protected boolean basis;
    @XmlElement(required = true)
    protected String nameausfuehrlich;
    @XmlElement(required = true)
    protected Integer wert;
    @XmlElement(required = true)
    protected String probe;
    @XmlElement(required = true)
    protected String probenwerte;
    @XmlElement(required = true)
    protected String nameausfuehrlichmitprobe;
    protected String at;
    protected String pa;
    @XmlElement(name = "sprachkomplexit\u00e4t")
    protected BigInteger sprachkomplexitaet;
    protected Boolean muttersprache;
    protected Boolean schriftmuttersprache;
    protected Boolean zweitlehrsprache;
    @XmlElement(required = true)
    protected String behinderung;
    protected boolean mirakelplus;
    protected boolean mirakelminus;
    protected boolean metatalent;
    @XmlElement(required = true)
    protected String bereich;
    @XmlElement(required = true)
    protected String komplexitaet;
    @XmlElement(required = true)
    protected String lernkomplexitaet;
    @XmlElement(required = true)
    protected String spezialisierungen;

    /**
     * Gets the value of the getName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the getName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the meisterhandwerk property.
     * 
     */
    public boolean isMeisterhandwerk() {
        return meisterhandwerk;
    }

    /**
     * Sets the value of the meisterhandwerk property.
     * 
     */
    public void setMeisterhandwerk(boolean value) {
        this.meisterhandwerk = value;
    }

    /**
     * Gets the value of the leittalent property.
     * 
     */
    public boolean isLeittalent() {
        return leittalent;
    }

    /**
     * Sets the value of the leittalent property.
     * 
     */
    public void setLeittalent(boolean value) {
        this.leittalent = value;
    }

    /**
     * Gets the value of the basis property.
     * 
     */
    public boolean isBasis() {
        return basis;
    }

    /**
     * Sets the value of the basis property.
     * 
     */
    public void setBasis(boolean value) {
        this.basis = value;
    }

    /**
     * Gets the value of the nameausfuehrlich property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameausfuehrlich() {
        return nameausfuehrlich;
    }

    /**
     * Sets the value of the nameausfuehrlich property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameausfuehrlich(String value) {
        this.nameausfuehrlich = value;
    }

    /**
     * Gets the value of the wert property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getWert() {
        return wert;
    }

    /**
     * Sets the value of the wert property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWert(Integer value) {
        this.wert = value;
    }

    /**
     * Gets the value of the probe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbe() {
        return probe;
    }

    /**
     * Sets the value of the probe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbe(String value) {
        this.probe = value;
    }

    /**
     * Gets the value of the probenwerte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbenwerte() {
        return probenwerte;
    }

    /**
     * Sets the value of the probenwerte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbenwerte(String value) {
        this.probenwerte = value;
    }

    /**
     * Gets the value of the nameausfuehrlichmitprobe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameausfuehrlichmitprobe() {
        return nameausfuehrlichmitprobe;
    }

    /**
     * Sets the value of the nameausfuehrlichmitprobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameausfuehrlichmitprobe(String value) {
        this.nameausfuehrlichmitprobe = value;
    }

    /**
     * Gets the value of the at property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAt() {
        return at;
    }

    /**
     * Sets the value of the at property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAt(String value) {
        this.at = value;
    }

    /**
     * Gets the value of the pa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPa() {
        return pa;
    }

    /**
     * Sets the value of the pa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPa(String value) {
        this.pa = value;
    }

    /**
     * Gets the value of the sprachkomplexitaet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSprachkomplexitaet() {
        return sprachkomplexitaet;
    }

    /**
     * Sets the value of the sprachkomplexitaet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSprachkomplexitaet(BigInteger value) {
        this.sprachkomplexitaet = value;
    }

    /**
     * Gets the value of the muttersprache property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMuttersprache() {
        return muttersprache;
    }

    /**
     * Sets the value of the muttersprache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMuttersprache(Boolean value) {
        this.muttersprache = value;
    }

    /**
     * Gets the value of the schriftmuttersprache property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSchriftmuttersprache() {
        return schriftmuttersprache;
    }

    /**
     * Sets the value of the schriftmuttersprache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSchriftmuttersprache(Boolean value) {
        this.schriftmuttersprache = value;
    }

    /**
     * Gets the value of the zweitlehrsprache property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZweitlehrsprache() {
        return zweitlehrsprache;
    }

    /**
     * Sets the value of the zweitlehrsprache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZweitlehrsprache(Boolean value) {
        this.zweitlehrsprache = value;
    }

    /**
     * Gets the value of the behinderung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehinderung() {
        return behinderung;
    }

    /**
     * Sets the value of the behinderung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehinderung(String value) {
        this.behinderung = value;
    }

    /**
     * Gets the value of the mirakelplus property.
     * 
     */
    public boolean isMirakelplus() {
        return mirakelplus;
    }

    /**
     * Sets the value of the mirakelplus property.
     * 
     */
    public void setMirakelplus(boolean value) {
        this.mirakelplus = value;
    }

    /**
     * Gets the value of the mirakelminus property.
     * 
     */
    public boolean isMirakelminus() {
        return mirakelminus;
    }

    /**
     * Sets the value of the mirakelminus property.
     * 
     */
    public void setMirakelminus(boolean value) {
        this.mirakelminus = value;
    }

    /**
     * Gets the value of the metatalent property.
     * 
     */
    public boolean isMetatalent() {
        return metatalent;
    }

    /**
     * Sets the value of the metatalent property.
     * 
     */
    public void setMetatalent(boolean value) {
        this.metatalent = value;
    }

    /**
     * Gets the value of the bereich property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBereich() {
        return bereich;
    }

    /**
     * Sets the value of the bereich property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBereich(String value) {
        this.bereich = value;
    }

    /**
     * Gets the value of the komplexitaet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomplexitaet() {
        return komplexitaet;
    }

    /**
     * Sets the value of the komplexitaet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomplexitaet(String value) {
        this.komplexitaet = value;
    }

    /**
     * Gets the value of the lernkomplexitaet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLernkomplexitaet() {
        return lernkomplexitaet;
    }

    /**
     * Sets the value of the lernkomplexitaet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLernkomplexitaet(String value) {
        this.lernkomplexitaet = value;
    }

    /**
     * Gets the value of the spezialisierungen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpezialisierungen() {
        return spezialisierungen;
    }

    /**
     * Sets the value of the spezialisierungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpezialisierungen(String value) {
        this.spezialisierungen = value;
    }

    @Override
    public String name() {
        return name;
    }

    @Override
    public String toString() {
        return "Talent{" +
                "name='" + name + '\'' +
                ", meisterhandwerk=" + meisterhandwerk +
                ", leittalent=" + leittalent +
                ", basis=" + basis +
                ", nameausfuehrlich='" + nameausfuehrlich + '\'' +
                ", wert=" + wert +
                ", probe='" + probe + '\'' +
                ", probenwerte='" + probenwerte + '\'' +
                ", nameausfuehrlichmitprobe='" + nameausfuehrlichmitprobe + '\'' +
                ", at='" + at + '\'' +
                ", pa='" + pa + '\'' +
                ", sprachkomplexitaet=" + sprachkomplexitaet +
                ", muttersprache=" + muttersprache +
                ", schriftmuttersprache=" + schriftmuttersprache +
                ", zweitlehrsprache=" + zweitlehrsprache +
                ", behinderung='" + behinderung + '\'' +
                ", mirakelplus=" + mirakelplus +
                ", mirakelminus=" + mirakelminus +
                ", metatalent=" + metatalent +
                ", bereich='" + bereich + '\'' +
                ", komplexitaet='" + komplexitaet + '\'' +
                ", lernkomplexitaet='" + lernkomplexitaet + '\'' +
                ", spezialisierungen='" + spezialisierungen + '\'' +
                '}';
    }
}
