// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.persistance.held;



public class HeldEntity {

	private Long id;

	private Long userId;
	private String name;
	private boolean isPublic;
	private boolean isActive = true;
	private boolean deleted;

	private Long gruppe;

	private Long key;

	public HeldEntity() {
	}

	public Long getId() {
		return this.id;
	}


	public Long getUserId() {
		return this.userId;
	}


	public String getName() {
		return this.name;
	}



	public boolean isPublic() {
		return this.isPublic;
	}


	public boolean isActive() {
		return this.isActive;
	}


	public boolean isDeleted() {
		return this.deleted;
	}


	public Long getGruppe() {
		return this.gruppe;
	}


	public void setId(final Long id) {
		this.id = id;
	}


	public void setUserId(final Long userId) {
		this.userId = userId;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setPublic(final boolean isPublic) {
		this.isPublic = isPublic;
	}


	public void setActive(final boolean isActive) {
		this.isActive = isActive;
	}


	public void setDeleted(final boolean deleted) {
		this.deleted = deleted;
	}


	public void setGruppe(final Long gruppe) {
		this.gruppe = gruppe;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}
}
