// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.persistance.held;


import java.time.LocalDateTime;

public class HeldEntity {

	private Long id;

	private Long userId;
	private String name;
    private Boolean isPublic;
    private Boolean isActive = true;
    private Boolean deleted;
	private LocalDateTime lockExpire;

	private Long gruppe;

	private Long key;

	public HeldEntity() {
	}

	public Long getId() {
		return this.id;
	}


	public Long getUserId() {
		return this.userId;
	}


	public String getName() {
		return this.name;
	}


    public Boolean isPublic() {
		return this.isPublic;
	}


    public Boolean isActive() {
		return this.isActive;
	}


    public Boolean isDeleted() {
		return this.deleted;
	}


	public Long getGruppe() {
		return this.gruppe;
	}


	public void setId(final Long id) {
		this.id = id;
	}


	public void setUserId(final Long userId) {
		this.userId = userId;
	}


	public void setName(final String name) {
		this.name = name;
	}


    public void setPublic(final Boolean isPublic) {
		this.isPublic = isPublic;
	}


    public void setActive(final Boolean isActive) {
		this.isActive = isActive;
	}


    public void setDeleted(final Boolean deleted) {
		this.deleted = deleted;
	}


	public void setGruppe(final Long gruppe) {
		this.gruppe = gruppe;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public LocalDateTime getLockExpire() {
		return lockExpire;
	}

	public void setLockExpire(LocalDateTime lockExpire) {
		this.lockExpire = lockExpire;
	}
}
