// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.persistance.held;


import de.failender.dgo.persistance.gruppe.GruppeEntity;

import javax.persistence.*;
import java.math.BigInteger;
import java.util.Date;

@Entity
@Table(name = "HELDEN")
public class HeldEntity {
	@Id
	private BigInteger id;
	@Column(name = "USER_ID")
	private Integer userId;
	@Column(name = "NAME")
	private String name;
	@Column(name = "PUBLIC")
	private boolean isPublic;
	@Column(name = "ACTIVE")
	private boolean isActive = true;
	@Column(name = "DELETED")
	private boolean deleted;
	@JoinColumn(name = "GRUPPE_ID")
	@ManyToOne
	private GruppeEntity gruppe;

	@Column(name = "HKEY")
	private Long key;
	@Column(name = "LOCK_EXPIRE")
	private Date lockExpire;

	public HeldEntity() {
	}

	public BigInteger getId() {
		return this.id;
	}


	public Integer getUserId() {
		return this.userId;
	}


	public String getName() {
		return this.name;
	}



	public boolean isPublic() {
		return this.isPublic;
	}


	public boolean isActive() {
		return this.isActive;
	}


	public boolean isDeleted() {
		return this.deleted;
	}


	public GruppeEntity getGruppe() {
		return this.gruppe;
	}


	public void setId(final BigInteger id) {
		this.id = id;
	}


	public void setUserId(final Integer userId) {
		this.userId = userId;
	}


	public void setName(final String name) {
		this.name = name;
	}


	public void setPublic(final boolean isPublic) {
		this.isPublic = isPublic;
	}


	public void setActive(final boolean isActive) {
		this.isActive = isActive;
	}


	public void setDeleted(final boolean deleted) {
		this.deleted = deleted;
	}


	public void setGruppe(final GruppeEntity gruppe) {
		this.gruppe = gruppe;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public Date getLockExpire() {
		return lockExpire;
	}

	public void setLockExpire(Date lockExpire) {
		this.lockExpire = lockExpire;
	}
}
