// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.persistance.held;

import de.failender.dgo.persistance.BaseEntity;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.UUID;

public class VersionEntity extends BaseEntity {
	private Long heldid;
	private int version;
	private LocalDateTime createdDate;
	private String lastEvent;
	private UUID cacheId;
	private Integer ap;

	public VersionEntity() {
	}

	public Long getHeldid() {
		return this.heldid;
	}

	public int getVersion() {
		return this.version;
	}

	public LocalDateTime getCreatedDate() {
		return this.createdDate;
	}

	public String getLastEvent() {
		return this.lastEvent;
	}

	public UUID getCacheId() {
		return this.cacheId;
	}

	public Integer getAp() {
		return this.ap;
	}

	public void setHeldid(final Long heldid) {
		this.heldid = heldid;
	}

	public void setVersion(final int version) {
		this.version = version;
	}

	public void setCreatedDate(final LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}

	public void setLastEvent(final String lastEvent) {
		this.lastEvent = lastEvent;
	}

	public void setCacheId(final UUID cacheId) {
		this.cacheId = cacheId;
	}

	public void setAp(final Integer ap) {
		this.ap = ap;
	}
}
