// Generated by delombok at Thu Nov 22 18:54:11 CET 2018
package de.failender.dgo.integration;

import de.failender.heldensoftware.xml.datenxml.Ereignis;

import java.util.List;

public class Difference {
    private Object oldValue;
    private Object newValue;
    private String name;
    private String tooltip;
    private int kosten;
    private List<Ereignis> ereignisse;


    public Difference(final Object oldValue, final Object newValue, final String name, final String tooltip, final int kosten, List<Ereignis> ereignisse) {
        this.oldValue = oldValue;
        this.newValue = newValue;
        this.name = name;
        this.tooltip = tooltip;
        this.kosten = kosten;
        this.ereignisse = ereignisse;
    }

    public Object getOldValue() {
        return this.oldValue;
    }

    public Object getNewValue() {
        return this.newValue;
    }

    public String getName() {
        return this.name;
    }

    public String getTooltip() {
        return this.tooltip;
    }

    public void setTooltip(final String tooltip) {
        this.tooltip = tooltip;
    }

    public int getKosten() {
        return kosten;
    }

    public List<Ereignis> getEreignisse() {
        return ereignisse;
    }
}
